import axios from 'axios';
import { logger } from '../utils/logger';
import type { DiffChange } from '../models/fileAnalysis';
import { RepoService } from './repoService';

export class GitHubService {
  private repoService: RepoService;

  constructor() {
    this.repoService = new RepoService();
  }

  /**
   * Helper to get GitHub token from user or environment
   */
  private getToken(): string {
    const token = process.env.GITHUB_TOKEN;
    if (!token) {
      throw new Error('GITHUB_TOKEN is not configured');
    }
    return token;
  }

  /**
   * Helper for API calls to GitHub
   */
  private async api(method: string, endpoint: string, data?: any) {
    const token = this.getToken();
    try {
      const response = await axios({
        method,
        url: `https://api.github.com${endpoint}`,
        headers: {
          'Authorization': `Bearer ${token}`,
          'Accept': 'application/vnd.github.v3+json',
          'X-GitHub-Api-Version': '2022-11-28'
        },
        data
      });
      return response.data;
    } catch (error: any) {
      logger.error(`GitHub API Error (${method} ${endpoint}):`, error.response?.data || error.message);
      throw new Error(error.response?.data?.message || 'GitHub API error');
    }
  }

  /**
   * Creates a PR for the given code changes
   */
  public async createPullRequest(
    repoId: string, 
    changes: DiffChange[], 
    title: string, 
    description: string,
    branchName: string
  ): Promise<any> {
    logger.info(`Creating PR for repo ${repoId} on branch ${branchName}`);
    
    // Note: In a real implementation, we would need to map repoId to actual GitHub owner/repo.
    // For this prototype, we'll assume the repoId is in the format "owner-repo" or similar
    // We will extract owner/repo from metadata.
    
    try {
      const metadata = await this.repoService.getRepoById(repoId);
      if (!metadata) {
        throw new Error(`Repository ${repoId} not found`);
      }
      const gitUrl = metadata.url; // e.g. https://github.com/owner/repo.git
      
      let owner = '';
      let repo = '';
      
      const match = gitUrl.match(/github\.com[/:]([^/]+)\/([^.]+)/);
      if (match) {
        owner = match[1];
        repo = match[2];
      } else {
        throw new Error('Could not parse GitHub repository URL from metadata');
      }

      // 1. Get default branch ref
      const repoInfo = await this.api('GET', `/repos/${owner}/${repo}`);
      const defaultBranch = repoInfo.default_branch;
      
      const refInfo = await this.api('GET', `/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`);
      const baseSha = refInfo.object.sha;

      // 2. Create new branch
      try {
        await this.api('POST', `/repos/${owner}/${repo}/git/refs`, {
          ref: `refs/heads/${branchName}`,
          sha: baseSha
        });
      } catch (e: any) {
        // If branch exists, we could handle it, but for simplicity let it bubble up
        throw new Error(`Failed to create branch: ${e.message}`);
      }

      // 3. Create blob for each change and build tree
      const treeItems = [];
      for (const change of changes) {
        if (change.changeType === 'delete') {
          // Marking as deleted in the tree
          treeItems.push({
            path: change.filePath,
            mode: '100644',
            type: 'blob',
            sha: null // Deletes the file
          });
        } else if (change.newContent) {
          const blob = await this.api('POST', `/repos/${owner}/${repo}/git/blobs`, {
            content: change.newContent,
            encoding: 'utf-8'
          });
          treeItems.push({
            path: change.filePath,
            mode: '100644',
            type: 'blob',
            sha: blob.sha
          });
        }
      }

      // 4. Create Tree
      const newTree = await this.api('POST', `/repos/${owner}/${repo}/git/trees`, {
        base_tree: baseSha,
        tree: treeItems
      });

      // 5. Create Commit
      const commit = await this.api('POST', `/repos/${owner}/${repo}/git/commits`, {
        message: title + '\\n\\n' + description,
        tree: newTree.sha,
        parents: [baseSha]
      });

      // 6. Update Branch Ref
      await this.api('PATCH', `/repos/${owner}/${repo}/git/refs/heads/${branchName}`, {
        sha: commit.sha
      });

      // 7. Create Pull Request
      const pr = await this.api('POST', `/repos/${owner}/${repo}/pulls`, {
        title,
        body: description + '\\n\\n_Generated by Atlas AI_',
        head: branchName,
        base: defaultBranch
      });

      return {
        success: true,
        prUrl: pr.html_url,
        prNumber: pr.number
      };
      
    } catch (e: any) {
      logger.error(`PR creation failed for ${repoId}`, e);
      throw e;
    }
  }
}
